export * from './MoviesPage/MoviesPage';
export * from './MovieDetailsPage/MovieDetailsPage';
export * from './MovieGenresPage/MovieGenresPage';
export * from './TvShowsPage/TvShowsPage';
export * from './SimilarPage/SimilarPage';
export * from './SearchPage/SearchPage';
export * from './UserPage/UserPage';
export * from './CinemaPage/CinemaPage';
export * from './NotFoundPage/NotFoundPage'