export * from './Header/Header';
export * from './Movies/Movies';
export * from './Movie/Movie';
export * from './MovieInfo/MovieInfo';
export * from './UserInfo/UserInfo';
export * from './StarsRating/StarsRating';
export * from './MovieDetails/MovieDetails';
export * from './MovieGenres/MovieGenres';
export * from './MovieGenreDetails/MovieGenreDetails';
export * from './TvShows/TvShows';
export * from './TvShow/TvShow';
export * from './Populars/Populars';
export * from './Popular/Popular';
export * from './Similar/Similar';
export * from './SimilarDetails/SimilarDetails'